<<<<<<< HEAD
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9yXs3QnOfRyLyN74QyilSfeKL-fVUxAQ',
    appId: '1:798489264335:web:b1bc7f6fe8dc5e68de37ba',
    messagingSenderId: '798489264335',
    projectId: 'invoice-receipt-generator-g7',
    authDomain: 'invoice-receipt-generator-g7.firebaseapp.com',
    storageBucket: 'invoice-receipt-generator-g7.firebasestorage.app',
  );
=======
import 'package:firebase_core/firebase_core.dart';

import 'config/app_config.dart';

class DefaultFirebaseOptions {
  const DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    final config = AppConfig.fromEnvironment();

    const appId = String.fromEnvironment('FIREBASE_APP_ID', defaultValue: '');
    const projectId = String.fromEnvironment('FIREBASE_PROJECT_ID', defaultValue: '');
    const messagingSenderId =
        String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID', defaultValue: '');
    const authDomain = String.fromEnvironment('FIREBASE_AUTH_DOMAIN', defaultValue: '');
    const storageBucket = String.fromEnvironment('FIREBASE_STORAGE_BUCKET', defaultValue: '');
    const measurementId =
        String.fromEnvironment('FIREBASE_MEASUREMENT_ID', defaultValue: '');

    final apiKey = config.firebaseApiKey;

    if (apiKey.isEmpty || appId.isEmpty || projectId.isEmpty || messagingSenderId.isEmpty) {
      throw StateError(
        'Missing Firebase configuration. Provide FIREBASE_API_KEY, FIREBASE_APP_ID, '
        'FIREBASE_PROJECT_ID, and FIREBASE_MESSAGING_SENDER_ID via --dart-define.',
      );
    }

    return FirebaseOptions(
      apiKey: apiKey,
      appId: appId,
      messagingSenderId: messagingSenderId,
      projectId: projectId,
      authDomain: _nullable(authDomain),
      storageBucket: _nullable(storageBucket),
      measurementId: _nullable(measurementId),
    );
  }

  static String? _nullable(String value) => value.isEmpty ? null : value;
>>>>>>> 17e15e6d3c6678e86b988a93144957fc05c6fe0f
}
