// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'config/app_config.dart';

class DefaultFirebaseOptions {
  const DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    final config = AppConfig.fromEnvironment();

    final apiKey = config.firebaseApiKey.isNotEmpty
        ? config.firebaseApiKey
        : _defaultWeb.apiKey;

    const appIdEnv = String.fromEnvironment('FIREBASE_APP_ID', defaultValue: '');
    final appId = appIdEnv.isNotEmpty ? appIdEnv : _defaultWeb.appId;

    const projectIdEnv =
        String.fromEnvironment('FIREBASE_PROJECT_ID', defaultValue: '');
    final projectId =
        projectIdEnv.isNotEmpty ? projectIdEnv : _defaultWeb.projectId;

    const messagingSenderIdEnv = String.fromEnvironment(
      'FIREBASE_MESSAGING_SENDER_ID',
      defaultValue: '',
    );
    final messagingSenderId = messagingSenderIdEnv.isNotEmpty
        ? messagingSenderIdEnv
        : _defaultWeb.messagingSenderId;

    const authDomainEnv =
        String.fromEnvironment('FIREBASE_AUTH_DOMAIN', defaultValue: '');
    final authDomain = authDomainEnv.isNotEmpty
        ? authDomainEnv
        : _defaultWeb.authDomain;

    const storageBucketEnv =
        String.fromEnvironment('FIREBASE_STORAGE_BUCKET', defaultValue: '');
    final storageBucket = storageBucketEnv.isNotEmpty
        ? storageBucketEnv
        : _defaultWeb.storageBucket;

    const measurementIdEnv =
        String.fromEnvironment('FIREBASE_MEASUREMENT_ID', defaultValue: '');
    final measurementId = measurementIdEnv.isNotEmpty
        ? measurementIdEnv
        : _defaultWeb.measurementId;

    return FirebaseOptions(
      apiKey: apiKey,
      appId: appId,
      messagingSenderId: messagingSenderId,
      projectId: projectId,
      authDomain: authDomain,
      storageBucket: storageBucket,
      measurementId: measurementId,
    );
  }

  static const FirebaseOptions _defaultWeb = FirebaseOptions(
    apiKey: 'AIzaSyC9yXs3QnOfRyLyN74QyilSfeKL-fVUxAQ',
    appId: '1:798489264335:web:b1bc7f6fe8dc5e68de37ba',
    messagingSenderId: '798489264335',
    projectId: 'invoice-receipt-generator-g7',
    authDomain: 'invoice-receipt-generator-g7.firebaseapp.com',
    storageBucket: 'invoice-receipt-generator-g7.firebasestorage.app',
  );
}
