import { InvoiceRecord } from './invoices';
import { DEFAULT_TEMPLATE_ID } from './templates';

export const sampleInvoices: InvoiceRecord[] = [
  {
    id: 'sample-001',
    clientName: 'Northwind Co.',
    clientEmail: 'billing@northwind.co',
    clientAddress: '400 Market Street, Portland, OR 97205',
    businessName: 'Atlas Studio',
    businessAddress: '88 Harbor Lane, Portland, OR',
    templateId: DEFAULT_TEMPLATE_ID,
    issueDate: '2024-11-12',
    dueDate: '2024-11-26',
    currency: 'USD',
    status: 'sent',
    taxRate: 0.07,
    notes: 'Payable by bank transfer. Late fees apply after 7 days.',
    lines: [
      { id: 'sample-001-line-1', description: 'Brand strategy sprint', quantity: 1, rate: 2800 },
      { id: 'sample-001-line-2', description: 'Retention playbook', quantity: 1, rate: 1200 },
    ],
    subtotal: 4000,
    taxAmount: 280,
    total: 4280,
    createdAt: '2024-11-12T14:20:00.000Z',
  },
  {
    id: 'sample-002',
    clientName: 'Mosaic Systems',
    clientEmail: 'ap@mosaicsystems.dev',
    clientAddress: '18 Innovation Way, Austin, TX 73301',
    businessName: 'Atlas Studio',
    businessAddress: '88 Harbor Lane, Portland, OR',
    templateId: 'classic-ledger',
    issueDate: '2024-10-04',
    dueDate: '2024-10-18',
    currency: 'USD',
    status: 'paid',
    taxRate: 0,
    notes: 'Thank you for the timely payment.',
    lines: [
      { id: 'sample-002-line-1', description: 'Full-stack implementation', quantity: 52, rate: 95 },
    ],
    subtotal: 4940,
    taxAmount: 0,
    total: 4940,
    createdAt: '2024-10-04T09:45:00.000Z',
  },
  {
    id: 'sample-003',
    clientName: 'Lumina Ventures',
    clientEmail: 'finance@luminaventures.ai',
    clientAddress: '600 Market Plaza, Suite 410, Seattle, WA 98101',
    businessName: 'Atlas Studio',
    businessAddress: '88 Harbor Lane, Portland, OR',
    templateId: 'aqua-ledger',
    issueDate: '2024-09-20',
    dueDate: '2024-09-30',
    currency: 'USD',
    status: 'overdue',
    taxRate: 0.05,
    notes: 'Second reminder sent October 2.',
    lines: [
      { id: 'sample-003-line-1', description: 'Quarterly analytics retainer', quantity: 1, rate: 2100 },
      { id: 'sample-003-line-2', description: 'Signal report addendum', quantity: 1, rate: 450 },
    ],
    subtotal: 2550,
    taxAmount: 127.5,
    total: 2677.5,
    createdAt: '2024-09-20T16:02:00.000Z',
  },
];
